APP_NAME: &APP_NAME slushots
DEVELOPMENT_TEAM: &DEVELOPMENT_TEAM PFP266U7G7
BUNDLE_ID_PREFIX: &BUNDLE_ID_PREFIX aswitch.me

settings:
  base:
    CURRENT_PROJECT_VERSION: 9
    MARKETING_VERSION: "1.1.7"
    DEVELOPMENT_TEAM: *DEVELOPMENT_TEAM
    IDEPreferLogStreaming: YES

name: *APP_NAME

options:
  bundleIdPrefix: *BUNDLE_ID_PREFIX
  developmentLanguage: en
  deploymentTarget:
    iOS: 15.0

targets:
  *APP_NAME:
    type: application
    platform: iOS
    sources:
      - path: slushots
    info:
      path: slushots/Info.plist
      properties:
        CFBundleDisplayName: "ProSlushots"
        CFBundleIdentifier: $(PRODUCT_BUNDLE_IDENTIFIER)
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchStoryboardName: LaunchScreen
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
          UISceneConfigurations:
            UIWindowSceneSessionRoleApplication:
              - UISceneConfigurationName: Default Configuration
                UISceneDelegateClassName: $(PRODUCT_MODULE_NAME).SceneDelegate
                UISceneStoryboardFile: Main
    settings:
      base:
        TARGETED_DEVICE_FAMILY: 1
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: true
      
